### ISSUE TITLE
Timeout After First iOS Message Sent

### ISSUE THREAD

**Issue by dicer2000** [fseydayucel/PushSharpHttpTwo#2]
### What version of PushSharp are you using?
Latest

### Describe your issue:
The first push attempt seems to work fine.  However, on the second push it always times out. 

### What are the steps required to reproduce this issue?
Send two iOS messages

### Please provide any Exception Stack Traces

 Notification Failure: The operation has timed out.    at HttpTwo.Http2Client.<Send>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpTwo.Http2Client.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpTwo.Http2Client.<Post>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Apple.ApnsHttp2Connection.<Send>d__10.MoveNext() in \PushSharpHttpTwo-master\PushSharp.Apple\ApnsHttp2Connection.cs:line 110
--- End of stack trace from previous location where exception was thrown ---

**Comment by rickstricker** [comment]
We are seeing the exact same thing. First push works.  Second push fails with timeout.

**Comment by dicer2000** [comment]
Ok, I've found out a little more about this... though, I don't have it working yet.  Going to start on it again now.  According to this thread: [https://github.com/Redth/HttpTwo/issues/7#issuecomment-315040613](https://github.com/Redth/HttpTwo/issues/7#issuecomment-315040613)

He says his version of the library fixes it: [https://github.com/Neio/HttpTwo](https://github.com/Neio/HttpTwo)

According to Neio, it's a fault in the underlying library HttpTwo.  So, I'm removing the copy that came down with the project and trying his version.

**Comment by dicer2000** [comment]
That new library seems to have fixed it.  I've got to do some extensive testing, but so far, so good.

A couple things: It seems it doesn't work with batch sending.  So, you can't do that in PushSharp like you used to.  Also, be sure you get the versions of hpack.dll that is in the HttpTwo library here:  [https://github.com/Neio/HttpTwo](https://github.com/Neio/HttpTwo).

Once I got them all on the same version of .Net, they started working.  I used 4.6.1.

**Comment by ellenkuipers** [comment]
> A couple things: It seems it doesn't work with batch sending. So, you can't do that in PushSharp like you used to. Also, be sure you get the versions of hpack.dll that is in the HttpTwo library here: https://github.com/Neio/HttpTwo.
> 

Hi @dicer2000,

Unfortunately I'm still facing the issue. I'm on .NET 4.7.2. I took the code from Redt, like https://github.com/Redth/PushSharp/blob/master/PushSharp.Apple/ApnsHttp2Configuration.cs etc. Added the HttpTwo from Neio (not the package that is on nuget). hpack version 1.0.2.29220 everywhere and we have:

  config_ = new ApnsHttp2Configuration(ApnsHttp2Configuration.ApnsServerEnvironment.Production, bytes, p12password)
            {
                InternalBatchingWaitPeriod = TimeSpan.FromMilliseconds(500),
                InternalBatchSize = 15
            };
            
One single messages succeed, but batch sending takes a long time and then throws System.TimeoutException: The operation has timed out.
Our service sends push to multiple apps, so we have multiple instances of the broker at the same time.

I have a couple of questions:
1. What are your settings on PushSharp's InternalBatchingWaitPeriod / InternalBatchSize etc.?
2. Is there still need to lock the http2Client? (I'm starting to think I need a **static** lock, an instance lock is not enough, but why exactly?)
3. Do we also need to lock the creation of the Http2Client?

Hoping you could help me.

**Comment by rickstricker** [comment]
We have the same setup as @ellenkuipers and are seeing the same results.  First notification goes thru, second one fails with a NullReferenceException.  The call to http2.post inside of ApnsHttp2Connection.Send throws the exception.  That's as far as we've narrowed down so far.

We have .NET 4.7.2 everywhere (even on HttpTwo project).  We're using HttpTwo project from https://github.com/Neio/HttpTwo and hpack version 1.0.2.29220.

Anybody have any ideas?

**Comment by dicer2000** [comment]
@ellenkuipers 
> One single messages succeed, but batch sending takes a long time and then throws System.TimeoutException: The operation has timed out.
> Our service sends push to multiple apps, so we have multiple instances of the broker at the same time.

Well, based on Neio's comments, it seems like batch processing does not work anymore.  I decided to do away with all batching and just send them one-by-one.  And that seems to work.

To answer your question: I don't do any of those configurations when I create the ApnsHttp2Configuration.  I just do:
```
config = new ApnsHttp2Configuration(ApnsHttp2Configuration.ApnsServerEnvironment.Production, appleCert, this.a.appleCertPassword);
```

Ultimately, I think we'll do away with all this and just move to Firebase.  This is all feeling too cobbled together to be used in production code.  But I'm hoping these changes to PushSharp will get us over the hump for Apple's deadline.

**Comment by dicer2000** [comment]
@rickstricker - I don't have many ideas for you except to say that it all lit up (and stayed going) when I had the combination of:
- PushSharpHttpTwo
- Neio's version of the httpTwo
- hpac (1.0.2.29220)

I did use .Net 4.6.1

One more thing -- I'm going to write in a separate thread message about another issue I found (and have sort of fixed).  It could be related.

**Comment by ellenkuipers** [comment]
@dicer2000 Thank you. And yes, Firebase is much more reliable. 

I have 2 more questions, if you don't mind. 

1. Did you change any of the settings in ApnsHttp2Configuration.cs to make this work? Settings like KeepAlivePeriod or ConnectionTimeout?
2. What do you mean (in code) with sending one-by-one? Do you re-create the Broker for every message? Or use the same broker (per p12) over and over again and just calling .Start() + .QueueNotification() for sending the message, like I do?

I notice I keep getting time-outs from time to time (using the default configuration now). Like in my Unit Test where I send 6000 messages to 1 device (using 2 "long-time existing" brokers - because I switch randomly between 2 apps)

**Comment by dicer2000** [comment]
@ellenkuipers 
> 1. Did you change any of the settings in ApnsHttp2Configuration.cs to make this work? Settings like KeepAlivePeriod or ConnectionTimeout?

No, but I was going to write that I did find another issue that is related.  After about an hour everything would stop due to a timeout.  So, I went to Apple's documentation and it showed that Apple expects the connection to be kept open for a long time.  It should only be closed if you are going to only send out one message per day.  (See https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html and search for "Best Practices for Managing Connections")

So, that led me to think that PushSharp/httptwo is letting that connection close after a timeout.  So, last night I did a test and sent a "ping" notification through every 2 minutes.  The connection stayed open and I was able to send notifications fine after a period of no activity (except the ping) for 8 hours.

> 2. What do you mean (in code) with sending one-by-one? Do you re-create the Broker for every message? Or use the same broker (per p12) over and over again and just calling .Start() + .QueueNotification() for sending the message, like I do?

Well, I just send the notifications out one-by-one.  I don't batch a bunch out at the same time.  However, the apnsBroker is the same one and does stay open.  And yes, I just use QueueNotification for sending messages.  So, maybe its the same as you.

**Comment by ellenkuipers** [comment]
@dicer2000 Oh that is genious! Yes indeed, I think you are correct, I remember reading that before. Maybe this knowledge can help me figure out the problem. Thank you for your help!

**Comment by dicer2000** [comment]
I did find another related issue: If I left it running without sending a message, everything would stop due to a timeout.  It's kind of like what you are describing, @rickstricker.  If I kept feeding them through with little time between tests, it worked fine.  But if I let it sit for an hour, it would fail.

So, I went to Apple's documentation and it showed that Apple expects the connection to be kept open for a long time. It should only be closed if you are going to only send out one message per day. (See [https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) and search for "Best Practices for Managing Connections")

That led me to think that PushSharp/httptwo is letting that connection close after a timeout. So, last night I did a test and sent a "ping" notification through every 2 minutes. The connection stayed open and I was able to send notifications fine after a period of no activity (except the ping) for 8 hours.

Now, I don't know if this is a good solution for the problem (sending a ping to keep alive).  What if the connection goes down?  I can never recover.  I just have to restart the service.

So, I think I might experiment with checking if the connection is open whenever I go to send a message.  Then if I find it closed, do the "Setup Apple" routine and finally send the message.

The only thing that we need to be careful of is that we don't looks like we are attacking their servers with too much open & close connections.  Per Apple's docs: 
> APNs treats rapid connection and disconnection as a denial-of-service attack.

That can't be good.

**Comment by silentdth** [comment]
Just a note here; I've forked Neio's repo and got the build and tests passing. I have not attempted to fix the batch implementation but am considering it before potentially making it available on Nuget.
https://github.com/silentdth/HttpTwo

**EDIT** Looks like Vlad's nuget library already has Neio's fix in it https://github.com/nvlad/pushsharp.apple.http2
https://www.nuget.org/packages/PushSharp.Apple.Http2/4.0.11.4
